### ISSUE TITLE
lower refresh rate onScroll

### ISSUE THREAD

**Issue by temaivanoff** [vitalif/dynamic-virtual-scroll#3]
```
Error: Maximum update depth exceeded.   
This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate.  
React limits the number of nested updates to prevent infinite loops.

```

**Comment by temaivanoff** [comment]
I understand the reason for the error, have suggestions and ideas how to get around? as a pure js logic in react option ?

**Comment by temaivanoff** [comment]
```js
  componentDidUpdate = (prevProps) => {
    if (prevProps.data !== this.props.data) {
      this.driver();
    }
  }
```

**Comment by vitalif** [comment]
> ```js
>   componentDidUpdate = (prevProps) => {
>     if (prevProps.data !== this.props.data) {
>       this.driver();
>     }
>   }
> ```

Just compare if anything changes instead of just calling setState()
Like here https://github.com/vitalif/dynamic-virtual-scroll/blob/master/DynamicVirtualScrollExample.js#L120
